export const GET_ALL_COUNTRIES_START_LOADING =
  "GET_ALL_COUNTRIES_START_LOADING";
export const GET_ALL_COUNTRIES_SUCCESS = "GET_ALL_COUNTRIES_SUCCESS";
export const GET_ALL_COUNTRIES_FAIL = "GET_ALL_COUNTRIES_FAIL";
export const GET_ALL_COUNTRIES_STOP_LOADING = "GET_ALL_COUNTRIES_STOP_LOADING";
